sudo: required
dist: bionic
language: go
go:
  - "1.14.x"
install: 
  - sudo apt-get install -qq pkg-config fuse build-essential
cache:
  apt: true
jobs:
  include:
      - stage: build
        name: 'Ubuntu 18 Build Test'
        script:
          - go run -race . -debug -dev
          - go build -i -v -ldflags="-X 'main.GitHash=$(git describe --always --long --dirty)' -X 'main.Version=$(date +'%y.%m.%d')'" github.com/duality-solutions/web-bridge
          - ./web-bridge -debug -dev